In [1222]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
import pandas as pd
import seaborn

np.random.seed(42)

%matplotlib inline

In [1223]:
df=pd.read_csv("diamonds.csv")

In [1224]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  53940 non-null  int64  
 1   carat       53940 non-null  float64
 2   cut         53940 non-null  object 
 3   color       53940 non-null  object 
 4   clarity     53940 non-null  object 
 5   depth       53940 non-null  float64
 6   table       53940 non-null  float64
 7   price       53940 non-null  int64  
 8   x           53940 non-null  float64
 9   y           53940 non-null  float64
 10  z           53940 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 4.5+ MB


In [1225]:
dummies=pd.get_dummies(df.loc[:,["cut","color","clarity"]])

df[dummies.columns] = dummies
df.drop(df.iloc[:,[0,2,3,4,5,6]],inplace=True, axis=1)


In [1226]:
train=df.sample(frac=0.8)
test=df.drop(train.index)
#train.drop("Unnamed: 0",inplace=True, axis=1)
#test.drop("Unnamed: 0",inplace=True,axis=1)
test.shape,train.shape

((10788, 25), (43152, 25))

In [1227]:
trainy=train["price"].to_numpy()
trainx=train.drop(["price"],axis=1)
testy=test["price"].to_numpy()

testx=test.drop(["price"],axis=1).to_numpy()

trainx=trainx.to_numpy()
testx.shape,testy.shape,trainx.shape[0]

train.shape,trainx.shape

((43152, 25), (43152, 24))

In [1228]:
class Linear_regression:
    def __init__(self,x,y,alpha=0.01):
        self.x=x
        self.y=y
        self.alpha=alpha
        self.samples,self.features=x.shape
        self.theta=np.ones(shape=(self.features, 1))
        #self.theta=np.reshape(self.theta,(self.theta.size,1))
        
    def predict(self,x):
        return np.dot(x, self.theta)
    
    def training(self,n=1000):
        while(n):
            
            self.y_hat=np.dot(self.x,self.theta)
            temp=self.y-self.y_hat
            
            self.gradient=np.dot(self.x.T,temp)
            #print(self.gradient.shape)            
            self.theta=self.theta+((self.alpha/self.samples)*self.gradient)
            #print(self.theta.shape)
            n=n-1
    
        return self.theta
    
    def testing(self,x,theta):
        self.test_x=x
        self.test_y=np.dot(x,self.theta)
        print(self.test_y)
        return self.test_y
        

In [1229]:
trainy=np.reshape(trainy,(trainy.size,1))
testy=np.reshape(testy,(testy.size,1))


In [1230]:
bias_col = np.ones(shape=(trainx.shape[0], 1))
trainx = np.hstack((bias_col, trainx))
bias_col = np.ones(shape=(testx.shape[0], 1))

testx=np.hstack((bias_col, testx))
bias_col.shape,trainx.shape

((10788, 1), (43152, 25))

In [1231]:
#trainx=trainx.transpose()
trainx.shape,trainy.shape

((43152, 25), (43152, 1))

In [1232]:
train.shape,trainx.shape,trainx

((43152, 25),
 (43152, 25),
 array([[1.  , 0.24, 3.97, ..., 0.  , 1.  , 0.  ],
        [1.  , 0.58, 5.44, ..., 0.  , 0.  , 1.  ],
        [1.  , 0.4 , 4.76, ..., 0.  , 0.  , 1.  ],
        ...,
        [1.  , 0.41, 4.71, ..., 0.  , 1.  , 0.  ],
        [1.  , 1.09, 6.62, ..., 0.  , 0.  , 1.  ],
        [1.  , 0.3 , 4.25, ..., 0.  , 0.  , 0.  ]]))

In [1233]:
lr=Linear_regression(trainx,trainy)
lr

In [1234]:
mp=lr.training(n=2000)

In [1235]:
np.dot(lr.x, mp), trainy

(array([[  80.66892791],
        [3158.32574073],
        [1680.64461303],
        ...,
        [1536.3659788 ],
        [7201.85898387],
        [ 150.14434338]]),
 array([[ 559],
        [2201],
        [1238],
        ...,
        [1169],
        [8364],
        [ 526]]))

In [1236]:
pred=lr.testing(testx,mp)
testx.shape

[[ -349.65458232]
 [ -562.98795161]
 [-1094.57206909]
 ...
 [ 3492.75321194]
 [ 3179.26222235]
 [ 3153.10085599]]


(10788, 25)

In [1237]:
mean_squared_error(testy,pred)

1789551.0821917276

In [1238]:
mean_squared_error(trainy, np.dot(lr.x, mp))

1922453.1964087524

In [1239]:
from sklearn.linear_model import LinearRegression

In [1240]:
sklr = LinearRegression(positive=True)
sklr.fit(trainx, trainy)

LinearRegression(positive=True)

In [1241]:
sklr.predict(testx)

array([[ -334.75],
       [ -909.25],
       [-2802.75],
       ...,
       [ 2780.5 ],
       [ 3184.75],
       [ 3293.75]])

In [1242]:
testy

array([[ 327],
       [ 338],
       [ 339],
       ...,
       [2756],
       [2756],
       [2757]])

In [1243]:
mean_squared_error(testy, sklr.predict(testx))

1276381.9082893028